spring:
  profiles:
    active: dev
server:
  servlet:
    context-path: "/ccm-common-framework"
info:
  app:
    name: Simple Template Project
    description: This is just a simple springboot project
    version: 1.0.0-SNAPSHOT
    environment: ${spring.profiles.active}

---
spring:
  config:
    activate:
      on-profile: dev
management:
  endpoints:
    web:
      exposure:
        include: "*"
